name: "Commit check"

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cargo install
        run: cargo install
      - name: WASM build
        run: wasm-pack build
      - name: Cargo test
        run: cargo test
        
