name: "Commit check"

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
  wasm:
    name: "WASM Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup wasm-pack
        run: cargo install wasm-pack
      - name: wasm-pack build
        run: wasm-pack build
  test:
    name: "Rust Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cargo build
        run: cargo build
      - name: Cargo test
        run: cargo test
        
